###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:5.6'
        working_dir: /api
        volumes:
            - '.:/api'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=aero-api
            - MYSQL_USER=aero
            - MYSQL_PASSWORD=aero
        ports:
            - '32002:3306'
        networks:
            - salvador

    webserver:
        image: 'nginx:alpine'
        working_dir: /api
        volumes:
            - '.:/api'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '32000:80'
        networks:
            - salvador

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /api
        volumes:
            - '.:/api'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - salvador

networks:
    salvador:
        driver: bridge